=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIPSTR1/testCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="testCase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="references"/>
        <xs:element ref="requirementText"/>
        <xs:element ref="description"/>
        <xs:element ref="dependencies"/>
        <xs:element ref="rules"/>
      </xs:sequence>
      <xs:attribute name="testable" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FALSE"/>
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="UNKNOWN"/>
            <xs:enumeration value="PARTIAL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="id">
    <xs:complexType>
      <xs:attribute name="requirementId" use="required" type="xs:NCName"/>
      <xs:attribute name="specification" use="required"/>
      <xs:attribute name="version" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="references">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reference" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reference">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              reference (element text): Requirement text copied from the specification.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="requirementText">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="name" type="xs:string" minOccurs="0"/>
        <xs:element name="location" type="xs:string" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="cardinality" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="0..1"/>
              <xs:enumeration value="0..n"/>
              <xs:enumeration value="1..1"/>
              <xs:enumeration value="1..n"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="level" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="MUST"/>
              <xs:enumeration value="SHOULD"/>
              <xs:enumeration value="MAY"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dependency">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              dependency (element text): Description of the dependency.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="rule"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="error"/>
        <xs:element ref="corpusPackages"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="error">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="message"/>
      </xs:sequence>
      <xs:attribute name="level" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ERROR"/>
            <xs:enumeration value="WARNING"/>
            <xs:enumeration value="INFO"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="message" type="xs:string"/>
  <xs:element name="corpusPackages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="package" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="package">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="path"/>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="isValid" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isValid attribute should be set TRUE for corpus packages that
          shouldn't generate any validation messages, including WARNING or INFO
          messages. The attribute is inappropriately named but changing it would
          break too many existing test cases.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isImplemented" use="optional" default="FALSE">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isImplemented attribute should be set FALSE for corpus packages that
          are defined in the test case but not implemented as a package. The attribute
          is optional and defaults to TRUE.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="path" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
</xs:schema>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP10/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="CSIP" version="2.1.0" requirementId="CSIP10"/>
  <references>
    <reference requirementId="CSIP10" URL="http://earkcsip.dilcis.eu/#CSIP10"/>
  </references>
  <requirementText>
    <name>Agent</name>
    <location>mets/metsHdr/agent</location>
    <description>
      A mandatory agent element records the software used to create the package. Other uses of agents may be described in any local implementations that extend the profile.
    </description>
    <cardinality>1..n</cardinality>
    <level>MUST</level>
  </requirementText>
  <description>
    mets/metsHdr/agent MUST exist one or more times.
  </description>
  <dependencies />
  <rules>
    <rule id="1">
      <description>mets/metsHdr/agent MUST exist one or more times.</description>
      <error level="ERROR">
        <message>
          mets/metsHdr/agent element does not exist. MUST be: element exists one or more times.
        </message>
      </error>
      <corpusPackages>
        <package name="mets-xml_metsHdr_agent_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/mets-xml_metsHdr_agent_not_exist</path>
          <description>
            METS.xml file has no mets/metsHdr/agent element.
          </description>
        </package>
        <package name="minimal_IP_with_1_representation" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements.
          </description>
        </package>
        <package name="minimal_IP_metsHdr_agent_2_instances" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_IP_metsHdr_agent_2_instances</path>
          <description>
            Minimal IP that matches all MUST requirements, and has two instances of mets/metsHdr/agent element.
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIPSTR13/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.0-DRAFT" requirementId="CSIPSTR13"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIPSTR13" URL="http://earkcsip.dilcis.eu/#CSIPSTR13" />
  </references>
  <requirementText> The representation folder SHOULD include a sub-folder named metadata which CAN include all metadata about the specific representation.
</requirementText>
  <!-- Textual description of the test case, may just be a repeat of the
  requirment text. -->
  <description>The representation folder SHOULD include a sub-folder named metadata which CAN include all metadata about the specific representation.
</description>
  <!-- List of requirments that this test case depends on in addition to the main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
    <!-- Individual validation rule entry, identified by a running number that's unique within the test case only -->
    <!-- Rule for the existence of a dmdSec element in mets.xml -->
    <rule id="1">
      <!-- Text description of the validation rule -->
      <description>The representation folder SHOULD include a sub-folder named 'metadata' </description>
      <!-- Details of the validation error generated by the message, can be one of: [ ERROR | WARNING | INFO ]-->
      <error level="WARNING">
        <!-- Expected error message when the rule is violated. -->
        <message>The representation folder does not include a sub-folder named `metadata`. It SHOULD include a sub-folder named 'metadata'  </message>
      </error>
      <corpusPackages>
        <!-- Details of corpus packages designed to test this validation rule. -->
        <package name="IP_18000_CSIPSTR13_1" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_1</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' named in camelcase</description>
        </package>
        <package name="IP_18000_CSIPSTR13_2" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_2</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra lowercase character in back</description>
        </package>
        <package name="IP_18000_CSIPSTR13_3" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_3</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP.  sub-folder named 'metadata' has extra lowercase character in front</description>
        </package>
        <package name="IP_18000_CSIPSTR13_4" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_4</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata'  has extra lowercase character in the middle. </description>
        </package>
        <package name="IP_18000_CSIPSTR13_5" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_5</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra uppercase character in back</description>
        </package>
        <package name="IP_18000_CSIPSTR13_6" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_6</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP.sub-folder named 'metadata' has extra uppercase character in front</description>
        </package>
        <package name="IP_18000_CSIPSTR13_7" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_7</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP.sub-folder named 'metadata' has extra uppercase character in middle</description>
        </package>
        <package name="IP_18000_CSIPSTR13_8" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_8</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata'  missing in root folder</description>
        </package>
        <package name="IP_18000_CSIPSTR13_9" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_9</path>
          <!-- Full description of corpus package features. -->
        <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra number sign in back </description>
        </package>
        <package name="IP_18000_CSIPSTR13_10" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_10</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra number sign in front. </description>
        </package>
        <package name="IP_18000_CSIPSTR13_11" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_11</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra number sign in middle. </description>
        </package>
        <package name="IP_18000_CSIPSTR13_12" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_12</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra sign in back. </description>
        </package>
        <package name="IP_18000_CSIPSTR13_13" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_13</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra sign in middle.</description>
        </package>
        <package name="IP_18000_CSIPSTR13_14" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_14</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' has extra sign in front.</description>
        </package>
        <package name="IP_18000_CSIPSTR13_15" isValid="FALSE" isImplemented="FALSE">
          <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_15</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. sub-folder named 'metadata' named in uppercase. </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id = "2">
      <description>Sub-folder named metadata CAN include all metadata about the specific representation. </description>
      <!-- Details of the validation error generated by the message, can be one of: [ ERROR | WARNING | INFO ]-->
      <error level="INFO">
        <!-- Expected error message when the rule is violated. -->
        <message>Sub-folder named 'metadata' contains following files:   </message>
      </error>
      <corpusPackages>
      <package name="IP_18000_CSIPSTR13_16" isValid="TRUE" isImplemented="FALSE">
        <path>/corpus/structure/CSIPSTR13/IP_18000_CSIPSTR13_16</path>
        <!-- Full description of corpus package features. -->
        <description>A package based on the folder stucture IP. Sub-folder named 'metadata' is empty</description>
      </package>
    </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP116/testCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.2.0" requirementId="CSIP116"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIP116" URL="http://earkcsip.dilcis.eu/#CSIP116"/>
  </references>
  <!-- The full text of the requirement. -->
  <requirementText>	Documentation file group reference pointer
    mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Documentation']/fptr/@FILEID
    A reference, by ID, to the “Documentation” file group.
    Related to the requirements CSIP60 which describes the “Documentation” file group and CSIP65 which describes the file group identifier.
  </requirementText>
  <!-- Textual description of the test case, extra notes beyond the requirment text. -->
  <description> All fileGrps with the @USE="Documentation" must also be presented in the structMap. CSIP96 and CSIP116 are intrinsically linked together and therefore is the same testcase.
  </description>
  <!-- List of requirments that this test case depends on in addition to the
  main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
    <dependency requirementId="CSIP96" URL="http://earkcsip.dilcis.eu/#CSIP96"></dependency>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
    <rule id="1">
      <description>A structMap[@LABEL='CSIP']/div/div[@LABEL='Documentation']/fptr must point to a fileGrp with @USE="Documentation"</description>
      <error level="ERROR">
        <message>The structMap[@LABEL='CSIP']/div/div[@LABEL='Documentation']/fptr points to a fileGrp that does not have @USE="Documentation"</message>
      </error>
      <corpusPackages>
        <package isValid="FALSE" isImplemented="TRUE" name="structMap_does_not_point_at_documentation">
          <path>invalid/structMap_does_not_point_at_documentation</path>
          <description>A package which has a documentation filepointer that points to a filegroup that does not have @USE="Documentation"</description>
        </package>
        <package isValid="TRUE" isImplemented="TRUE" name="minimal_IP_with_1_representation">
          <path>valid/minimal_IP_with_1_representation</path>
          <description>Minimal IP</description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/structure/CSIPSTR6/testCase.xml
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.0-DRAFT" requirementId="CSIPSTR6"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIPSTR6" URL="http://earkcsip.dilcis.eu/#CSIPSTR6"/>
  </references>
  <!-- The full text of the requirement. -->
  <requirementText> If preservation metadata are available, they SHOULD be included in sub-folder preservation.
  </requirementText>
  <!-- Textual description of the test case, extra notes beyond the requirment text. -->
  <description></description>
  <!-- List of requirments that this test case depends on in addition to the
  main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP24/testCase.xml
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.1.0" requirementId="CSIP24"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIP24" URL="http://earkcsip.dilcis.eu/#CSIP24"/>
  </references>
  <!-- The full text of the requirement. -->
  <requirementText>dmdSec/mdRef/@xlink:href. The actual location of the resource. This specification recommends recording a URL type filepath within this attribute.</requirementText>
  <!-- Textual description of the test case, extra notes beyond the requirment text. -->
  <description>dmdSec/mdRef/@xlink:href </description>
  <!-- List of requirments that this test case depends on in addition to the
  main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
    <rule id="1">
      <description>@xlink:href must exist in METS.xml</description>
      <error level="ERROR">
        <message>There is no dmdSec/mdRef/@xlink:href in METS.xml. In METS.XML the dmdSec/mdRef-element MUST have the attribute: @xlink:href and its value must be a URL type filepath. </message>
      </error>
      <corpusPackages>
        <package isValid="FALSE" name="IP_18000_CSIP24_1" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP24_1</path>
          <description>There is no @xlink:href in METS.xml</description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>It is recommended to have a URL type filepath value in @xlink:href</description>
      <error level="WARNING">
        <message>In METS.XML the value in dmdSec/mdRef/@xlink:href SHOULD be a URL type filepath. The current value is not a URL type filepath </message>
      </error>
      <corpusPackages>
        <package isValid="FALSE" name="IP_18000_CSIP24_2" isImplemented="TRUE">
          <path>valid/IP_18000_CSIP24_2</path>
          <description>There is no value in dmdSec/mdRef/@xlink:href</description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>
