=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIPSTR1/testCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="testCase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="references"/>
        <xs:element ref="requirementText"/>
        <xs:element ref="description"/>
        <xs:element ref="dependencies"/>
        <xs:element ref="rules"/>
      </xs:sequence>
      <xs:attribute name="testable" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FALSE"/>
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="UNKNOWN"/>
            <xs:enumeration value="PARTIAL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="id">
    <xs:complexType>
      <xs:attribute name="requirementId" use="required" type="xs:NCName"/>
      <xs:attribute name="specification" use="required"/>
      <xs:attribute name="version" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="references">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reference" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reference">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              reference (element text): Requirement text copied from the specification.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="requirementText">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="name" type="xs:string" minOccurs="0"/>
        <xs:element name="location" type="xs:string" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="cardinality" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="0..1"/>
              <xs:enumeration value="0..n"/>
              <xs:enumeration value="1..1"/>
              <xs:enumeration value="1..n"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="level" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="MUST"/>
              <xs:enumeration value="SHOULD"/>
              <xs:enumeration value="MAY"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dependency">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              dependency (element text): Description of the dependency.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="rule"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="error"/>
        <xs:element ref="corpusPackages"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="error">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="message"/>
      </xs:sequence>
      <xs:attribute name="level" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ERROR"/>
            <xs:enumeration value="WARNING"/>
            <xs:enumeration value="INFO"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="message" type="xs:string"/>
  <xs:element name="corpusPackages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="package" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="package">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="path"/>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="isValid" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isValid attribute should be set TRUE for corpus packages that
          shouldn't generate any validation messages, including WARNING or INFO
          messages. The attribute is inappropriately named but changing it would
          break too many existing test cases.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isImplemented" use="optional" default="FALSE">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isImplemented attribute should be set FALSE for corpus packages that
          are defined in the test case but not implemented as a package. The attribute
          is optional and defaults to TRUE.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="path" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
</xs:schema>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIPSTR11/testCase.xml
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.2.0" requirementId="CSIPSTR11"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIPSTR11" URL="http://earkcsip.dilcis.eu/#CSIPSTR11" />
  </references>
  <requirementText> The representation folder SHOULD include a sub-folder named data which includes all data constituting the representation.
</requirementText>
  <!-- Textual description of the test case, may just be a repeat of the
  requirment text. -->
  <description>The representation folder SHOULD include a sub-folder named data which includes all data constituting the representation.
</description>
  <!-- List of requirments that this test case depends on in addition to the main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
    <!-- Individual validation rule entry, identified by a running number that's unique within the test case only -->
    <!-- Rule for the existence of a dmdSec element in mets.xml -->

    <rule id="1">
      <!-- Text description of the validation rule -->
      <description>The representation folder SHOULD include a sub-folder named data </description>
      <!-- Details of the validation error generated by the message, can be one of: [ ERROR | WARNING | INFO ]-->
      <error level="WARNING">
        <!-- Expected error message when the rule is violated. -->
        <message>The representation folder does not include a sub-folder named `data`. It SHOULD include a sub-folder named data  </message>
      </error>
      <corpusPackages>
        <!-- Details of corpus packages designed to test this validation rule. -->
        <package name="IP_18000_CSIPSTR11_1" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_1</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' named in camelcase</description>
        </package>
        <package name="IP_18000_CSIPSTR11_2" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_2</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra lowercase character in back</description>
        </package>
        <package name="IP_18000_CSIPSTR11_3" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_3</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP.  Sub-folder 'data' has extra lowercase character in front</description>
        </package>
        <package name="IP_18000_CSIPSTR11_4" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_4</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data'  has extra lowercase character in the middle. </description>
        </package>
        <package name="IP_18000_CSIPSTR11_5" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_5</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra uppercase character in back</description>
        </package>
        <package name="IP_18000_CSIPSTR11_6" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_6</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP.Sub-folder 'data' has extra uppercase character in front</description>
        </package>
        <package name="IP_18000_CSIPSTR11_7" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_7</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP.Sub-folder 'data' has extra uppercase character in middle</description>
        </package>
        <package name="IP_18000_CSIPSTR11_8" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_8</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data'  missing in root folder</description>
        </package>
        <package name="IP_18000_CSIPSTR11_9" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_9</path>
          <!-- Full description of corpus package features. -->
        <description>A package based on the folder stucture IP. Sub-folder 'data' has extra number sign in back </description>
        </package>
        <package name="IP_18000_CSIPSTR11_10" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_10</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra number sign in front. </description>
        </package>
        <package name="IP_18000_CSIPSTR11_11" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_11</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra number sign in middle. </description>
        </package>
        <package name="IP_18000_CSIPSTR11_12" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_12</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra sign in back. </description>
        </package>
        <package name="IP_18000_CSIPSTR11_13" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_13</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra sign in middle.</description>
        </package>
        <package name="IP_18000_CSIPSTR11_14" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_14</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' has extra sign in front.</description>
        </package>
        <package name="IP_18000_CSIPSTR11_15" isValid="FALSE" isImplemented="TRUE">
          <path>valid/CSIPSTR11_15</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the folder stucture IP. Sub-folder 'data' named in uppercase. </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/structure/CSIPSTR4/testCase.xml
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.0-DRAFT" requirementId="CSIPSTR4"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIPSTR4" URL="http://earkcsip.dilcis.eu/#CSIPSTR4" />
  </references>
  <requirementText> The Information Package root folder MUST include a metadata file named METS.xml, which MUST include information about the identity and structure of the package and its components at a minimum down to a general description or pointer to each representation. </requirementText>
  <!-- Textual description of the test case, may just be a repeat of the
  requirment text. -->
  <description>The Information Package root folder MUST include a metadata file named METS.xml, which MUST include information about the identity and structure of the package and its components at a minimum down to a general description or pointer to each representation.</description>
  <!-- List of requirments that this test case depends on in addition to the main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
    <!-- Individual validation rule entry, identified by a running number that's unique within the test case only -->
    <!-- Rule for the existence of a dmdSec element in mets.xml -->
    
    <rule id="1">
      <!-- Text description of the validation rule -->
      <description>The Information Package folder MUST include a metadata file named `METS.xml`</description>
      <!-- Details of the validation error generated by the message, can be one of: [ ERROR | WARNING | INFO ]-->
      <error level="ERROR">
        <!-- Expected error message when the rule is violated. -->
        <message>The Information Package folder does not include METS.xml file. It MUST include a metadata file named `METS.xml` </message>
      </error>
      <corpusPackages>
        <!-- Details of corpus packages designed to test this validation rule. -->
        <package name="IP_18000_CSIPSTR4_1" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_1</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml named in camelcase (Mets.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_2" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_2</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has extra lowercase character at back of the filename(METSa.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_3" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_3</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas.  File METS.xml has extra lowercase character in front of the filename(aMETS.xml)</description>  
        </package>
        <package name="IP_18000_CSIPSTR4_4" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_4</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has extra lowercase character in the middle of the filename (MEaTS.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_5" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_5</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has extra uppercase character at back of the filename(METSA.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_6" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_6</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas.File METS.xml has extra uppercase character in front of the filename(AMETS.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_7" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_7</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has extra uppercase character in the middle of the filename (MEATS.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_8" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_8</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has extension inside filename (METS.xml.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_9" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_9</path>
          <!-- Full description of corpus package features. -->
        <description>A package based on the minimal IP with schemas. METS.xml named in lowercase (mets.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_10" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_10</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. Root folder does not include .xml file</description>
        </package>
        <package name="IP_18000_CSIPSTR4_11" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_11</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has a number at the back of the filename (METS1.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_12" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_12</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has a number in the front of the filename (1METS.xml</description>
        </package>
        <package name="IP_18000_CSIPSTR4_13" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_13</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has a number in the middle of the filename (ME1TS.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_14" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_14</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. Root folder includes a file named test.xml. METS.xml is missing.</description>
        </package>
        <package name="IP_18000_CSIPSTR4_15" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_15</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has sign after the required filename (METS_old.xml)</description>
        </package>
          <package name="IP_18000_CSIPSTR4_16" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_16</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas.File METS.xml has sign before the required filename (old_METS.xml)</description>
        </package>
        <package name="IP_18000_CSIPSTR4_17" isValid="FALSE">
          <path>/corpus/structure/CSIPSTR4/IP_18000_CSIPSTR4_17</path>
          <!-- Full description of corpus package features. -->
          <description>A package based on the minimal IP with schemas. File METS.xml has sign in the middle of the required filename (ME_TS.xml)</description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/SIP/SIP35/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="SIP" version="2.2.0" requirementId="SIP35"/>
  <references>
    <reference requirementId="SIP35" URL="https://earksip.dilcis.eu/#SIP35"/>
  </references>
  <requirementText>
    <name>File format registry key</name>
    <location>mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY</location>
    <description>
      Key of the file format in the registry when use of PREMIS has not been agreed upon in the submission agreement.
	  Example: “fmt/101”
    </description>
    <cardinality>0..1</cardinality>
    <level>MAY</level>
  </requirementText>
  <description>
    mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY MAY exist.
    If mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY exists then it MUST have a value.
    The value MUST record the key of the file format in the registry.<!-- Untestable -->
	If mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY exists then the use of PREMIS
      MUST not have been agreed upon in the submission agreement.<!-- Untestable
      under the current wording as it would require parsing and interpreting the
      submission agreement, which is not a machine-readable document. If the
      requirement was about the presence of PREMIS metadata, some automated
      tests could be performed for the presence of PREMIS XML files or their
      references in amdSec/digiprovMD elements. However, such tests would likely
      remain inconclusive as "the presence of PREMIS" can be interpreted in
      multiple ways. -->
  </description>
  <dependencies>
    <dependency requirementId="Chapter_5.4" URL="https://earkcsip.dilcis.eu/#useofpremis">
      @sip:FILEFORMATKEY should be used only if the use of PREMIS has not been agreed upon in the submission agreement.
    </dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY MAY exist.</description>
      <error level="INFO">
        <message>
          mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY does not exist. MAY be: the attribute exists and its value records the key of the file format in the registry.
        </message>
      </error>
      <corpusPackages>
        <package name="FILEFORMATKEY_not_exist" isValid="FALSE" isImplemented="FALSE">
          <path>invalid/FILEFORMATKEY_not_exist</path>
          <description>
            SIP where the METS.xml file has a mets/fileSec/fileGrp/file element with no @sip:FILEFORMATKEY attribute.
          </description>
        </package>
        <package name="minimal_SIP_plus_mets_SHOULD_MAY_items" isValid="TRUE" isImplemented="FALSE">
          <path>valid/minimal_SIP_plus_mets_SHOULD_MAY_items</path>
          <description>
            Minimal SIP that matches all MUST requirements, plus all SHOULD and MAY requirements (both for elements and attributes).
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>If mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY exists then it MUST have a value.</description>
      <error level="WARNING"><!-- Empty values are not explicitly prohibited but go against the logic of the specification. -->
        <message>
          mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY value is empty. MUST be: if the attribute exists then it MUST have a value that records the key of the file format in the registry.
        </message>
      </error>
      <corpusPackages>
        <package name="FILEFORMATKEY_value_empty" isValid="FALSE" isImplemented="FALSE">
          <path>invalid/FILEFORMATKEY_value_empty</path>
          <description>
            A SIP with METS.xml file that has a mets/fileSec/fileGrp/file/@sip:FILEFORMATKEY = "".
          </description>
        </package>
        <package name="minimal_SIP_plus_mets_SHOULD_MAY_items" isValid="TRUE" isImplemented="FALSE">
          <path>valid/minimal_SIP_plus_mets_SHOULD_MAY_items</path>
          <description>
            Minimal SIP that matches all MUST requirements, plus all SHOULD and MAY requirements (both for elements and attributes).
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/structure/CSIPSTR8/testCase.xml
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.0-DRAFT" requirementId="CSIPSTR8"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIPSTR8" URL="http://earkcsip.dilcis.eu/#CSIPSTR8"/>
  </references>
  <!-- The full text of the requirement. -->
  <requirementText>  If any other metadata are available, they CAN be included in separate sub-folders, for example an additional folder named other.
  </requirementText>
  <!-- Textual description of the test case, extra notes beyond the requirment text. -->
  <description></description>
  <!-- List of requirments that this test case depends on in addition to the
  main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
  </rules>
</testCase>
