=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIPSTR1/testCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="testCase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="references"/>
        <xs:element ref="requirementText"/>
        <xs:element ref="description"/>
        <xs:element ref="dependencies"/>
        <xs:element ref="rules"/>
      </xs:sequence>
      <xs:attribute name="testable" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FALSE"/>
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="UNKNOWN"/>
            <xs:enumeration value="PARTIAL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="id">
    <xs:complexType>
      <xs:attribute name="requirementId" use="required" type="xs:NCName"/>
      <xs:attribute name="specification" use="required"/>
      <xs:attribute name="version" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="references">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reference" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reference">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              reference (element text): Requirement text copied from the specification.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="requirementText">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="name" type="xs:string" minOccurs="0"/>
        <xs:element name="location" type="xs:string" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="cardinality" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="0..1"/>
              <xs:enumeration value="0..n"/>
              <xs:enumeration value="1..1"/>
              <xs:enumeration value="1..n"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="level" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="MUST"/>
              <xs:enumeration value="SHOULD"/>
              <xs:enumeration value="MAY"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dependency">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              dependency (element text): Description of the dependency.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="rule"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="error"/>
        <xs:element ref="corpusPackages"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="error">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="message"/>
      </xs:sequence>
      <xs:attribute name="level" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ERROR"/>
            <xs:enumeration value="WARNING"/>
            <xs:enumeration value="INFO"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="message" type="xs:string"/>
  <xs:element name="corpusPackages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="package" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="package">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="path"/>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="isValid" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isValid attribute should be set TRUE for corpus packages that
          shouldn't generate any validation messages, including WARNING or INFO
          messages. The attribute is inappropriately named but changing it would
          break too many existing test cases.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isImplemented" use="optional" default="FALSE">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isImplemented attribute should be set FALSE for corpus packages that
          are defined in the test case but not implemented as a package. The attribute
          is optional and defaults to TRUE.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="path" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
</xs:schema>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP64/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="CSIP" version="2.0.4" requirementId="CSIP64"/>
  <references>
    <reference requirementId="CSIP64" URL="http://earkcsip.dilcis.eu/#CSIP64"/>
  </references>
  <requirementText>
    <name>Description of the use of the file group</name>
    <location>mets/fileSec/fileGrp/@USE</location>
    <description>
      The value in the mets/fileSec/fileGrp/@USE is the name of the whole folder structure to the data, e.g "Documentation", "Schemas", "Representations/preingest" or "Representations/submission/data".
    </description>
    <cardinality>1..1</cardinality>
    <level>MUST</level>
  </requirementText>
  <!--  Assumptions:
        - VocabularyFileGrpAndStructMapDivisionLabel is mandatory, despite it
          not being mentioned in the requirement text. This follows from the
          definitions of CSIP60, 113 and 114.
        - The match between fileGrp/@USE and folder path must be case insensitive
          because VocabularyFileGrpAndStructMapDivisionLabel mandates values
          with capital first letter but CSIPSTR5 - 16 mandate lowercase folder
          names.
  -->
  <description>
    For each mets/fileSec/fileGrp that exists, mets/fileSec/fileGrp/@USE MUST exist.
    mets/fileSec/fileGrp/@USE value MUST begin with or equal to a value from VocabularyFileGrpAndStructMapDivisionLabel.
    mets/fileSec/fileGrp/@USE value MUST match an existing folder path in the package, case insensitive.
  </description>
  <dependencies>
    <dependency requirementId="VocabularyFileGrpAndStructMapDivisionLabel" URL="https://earkcsip.dilcis.eu/#VocabularyFileGrpAndStructMapDivisionLabel">
      https://earkcsip.dilcis.eu/schema/CSIPVocabularyFileGrpAndStructMapDivisionLabel.xml
    </dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>For each mets/fileSec/fileGrp that exists, mets/fileSec/fileGrp/@USE MUST exist.</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@USE attribute does not exist. MUST be: For each mets/fileSec/fileGrp that exists, mets/fileSec/fileGrp/@USE MUST exist.
        </message>
      </error>
      <corpusPackages>
        <package name="fileGrp_USE_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/fileGrp_USE_not_exist</path>
          <description>
            METS.xml file has a mets/fileSec/fileGrp with no mets/fileSec/fileGrp/@USE attribute.
          </description>
        </package>
        <package name="minimal_IP_with_1_representation" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements, plus all SHOULD requirements (both for elements and attributes), incl.:
            - the folder "documentation" exists (CSIPSTR16)
            - a fileGrp exists that has mets/fileSec/fileGrp/@USE = "Documentation".
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>mets/fileSec/fileGrp/@USE value MUST begin with or equal to a value from VocabularyFileGrpAndStructMapDivisionLabel.</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@USE attribute has incorrect value. MUST be: mets/fileSec/fileGrp/@USE value MUST begin with or equal to a value from VocabularyFileGrpAndStructMapDivisionLabel.
        </message>
      </error>
      <corpusPackages>
        <package name="fileGrp_USE_vocabulary_mismatch" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/fileGrp_USE_vocabulary_mismatch</path>
          <description>
            METS.xml file has mets/fileSec/fileGrp/@USE = "random_string_e2368caa08a1cbbe2e8d5b96ab34a41e".
          </description>
        </package>
        <!--  Ideally, there should be a valid IP for each specific vocabulary
              value, as this is the only certain way to test that the validator
              accepts any one of them. This should be automated as
              VocabularyFileGrpAndStructMapDivisionLabel currently allows 4
              different values. -->
        <package name="minimal_IP_with_1_representation" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements, plus all SHOULD requirements (both for elements and attributes), incl.:
            - the folder "documentation" exists (CSIPSTR16)
            - a fileGrp exists that has mets/fileSec/fileGrp/@USE = "Documentation"
            - mets/fileSec/fileGrp/@USE is properly declared for all fileGrp elements.
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="3">
      <description>mets/fileSec/fileGrp/@USE value MUST match an existing folder path in the package, case insensitive.</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@USE attribute has incorrect value. MUST be: mets/fileSec/fileGrp/@USE value MUST match an existing folder path in the package, case insensitive.
        </message>
      </error>
      <corpusPackages>
        <package name="fileGrp_USE_folder_mismatch" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/fileGrp_USE_folder_mismatch</path>
          <description>
            METS.xml file where:
            - mets/fileSec/fileGrp/@USE = "Representations/random_string_96ab34a41e".
            - no folder exists with the name "Representations/random_string_96ab34a41e".
            Note: the value "Representations/random_string_96ab34a41e" violates
            only the folder path match, but is OK for vocabulary match (i.e.
            begins with a value from the vocabulary).
          </description>
        </package>
        <package name="minimal_IP_with_1_representation" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements, plus all SHOULD requirements (both for elements and attributes), incl.:
            - the folder "documentation" exists (CSIPSTR16)
            - a fileGrp exists that has mets/fileSec/fileGrp/@USE = "Documentation"
            - mets/fileSec/fileGrp/@USE is properly declared for all fileGrp elements.
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/SIP/SIP34/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="SIP" version="2.2.0" requirementId="SIP34"/>
  <references>
    <reference requirementId="SIP34" URL="https://earksip.dilcis.eu/#SIP34"/>
  </references>
  <requirementText>
    <name>File format registry</name>
    <location>mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY</location>
    <description>
      The name of the format registry used to identify the file format when the use of PREMIS has not been agreed upon in the submission agreement.
	  Example: “PRONOM”
    </description>
    <cardinality>0..1</cardinality>
    <level>MAY</level>
  </requirementText>
  <description>
    mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY MAY exist.
    If mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY exists then it MUST have a value.
    The value MUST record the name of the format registry used to identify the file format.<!-- Untestable -->
    If mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY exists then the use of PREMIS
      MUST not have been agreed upon in the submission agreement.<!-- Untestable
      under the current wording as it would require parsing and interpreting the
      submission agreement, which is not a machine-readable document. If the
      requirement was about the presence of PREMIS metadata, some automated
      tests could be performed for the presence of PREMIS XML files or their
      references in amdSec/digiprovMD elements. However, such tests would likely
      remain inconclusive as "the presence of PREMIS" can be interpreted in
      multiple ways. -->
  </description>
  <dependencies>
    <dependency requirementId="Chapter_5.4" URL="https://earkcsip.dilcis.eu/#useofpremis">
      @sip:FILEFORMATREGISTRY should be used only if the use of PREMIS has not been agreed upon in the submission agreement.
    </dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY MAY exist.</description>
      <error level="INFO">
        <message>
          mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY does not exist. MAY be: the attribute exists and its value records the name of the format registry used to identify the file format.
        </message>
      </error>
      <corpusPackages>
        <package name="FILEFORMATREGISTRY_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/FILEFORMATREGISTRY_not_exist</path>
          <description>
            SIP where the METS.xml file has a mets/fileSec/fileGrp/file element with no @sip:FILEFORMATREGISTRY attribute.
          </description>
        </package>
        <package name="minimal_SIP_plus_mets_SHOULD_MAY_items" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_SIP_plus_mets_SHOULD_MAY_items</path>
          <description>
            Minimal SIP that matches all MUST requirements, plus all SHOULD and MAY requirements (both for elements and attributes).
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>If mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY exists then it MUST have a value.</description>
      <error level="WARNING"><!-- Empty values are not explicitly prohibited but go against the logic of the specification. -->
        <message>
          mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY value is empty. MUST be: if the attribute exists then it MUST have a value that records the format registry used to identify the file format.
        </message>
      </error>
      <corpusPackages>
        <package name="FILEFORMATREGISTRY_value_empty" isValid="FALSE" isImplemented="TRUE" >
          <path>invalid/FILEFORMATREGISTRY_value_empty</path>
          <description>
            A SIP with METS.xml file that has a mets/fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY = "".
          </description>
        </package>
        <package name="minimal_SIP_plus_mets_SHOULD_MAY_items" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_SIP_plus_mets_SHOULD_MAY_items</path>
          <description>
            Minimal SIP that matches all MUST requirements, plus all SHOULD and MAY requirements (both for elements and attributes).
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP103/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="FALSE">
    <id specification="E-ARK CSIP" version="2.0.4" requirementId="CSIP103"/>
    <references>
    <reference requirementId="CSIP103" URL="https://earkcsip.dilcis.eu/#CSIP103"/>
  </references>
  <requirementText>
    <name>Content division label</name>
    <location>mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Representations']</location>
    <description>
      The package's content division div element must have the @LABEL attribute value "Representations", taken from the vocabulary.
      See also: File group names
    </description>
    <cardinality>1..1</cardinality>
    <level>MUST</level>
  </requirementText>
  <description>
    CSIP103 seems identical to CSIP101, but the authors of the
    specification had a distinction in mind: "â€¦ the first requirement
    defines whether the division itself is mandatory, the second defines
    the required label value," see the issue "Redundancies and
    incompatible priority levels" at
    https://github.com/DILCISBoard/E-ARK-CSIP/issues/570. The cases of
    there being no 'Representations' division or more than one
    'Representations' division are handled in CSIP101. Consequently, there
    is only one rule left for CSIP103:
      If the 'Representations' division exists, it MUST have @LABEL='Representations'.

    This, however, is not reliably testable with algorithms of reasonable
    complexity. Detecting a representations division that is not marked
    @LABEL='Representations' would require analysing indirect indicators (e.g. a
    structMap/div with references to files in the /representations folder), but
    these cannot give enough confidence to announce a violation of a MUST
    rule.

    In sum, only valid IPs are meaningful for CSIP103 and the requirement is
    effectively not testable.
  </description>
  <dependencies>
    <dependency requirementId="CSIP101" URL="https://earkcsip.dilcis.eu/#CSIP101"></dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>If the schema division exists, it MUST have @LABEL='Representations'.</description>
      <error level="ERROR">
        <message>If the schema division exists, it MUST have @LABEL='Representations'.</message>
      </error>
      <corpusPackages>
        <package isValid="TRUE" isImplemented="FALSE" name="minimal_IP_with_no_representations">
          <path>valid/minimal_IP_with_no_representations</path>
          <description>Minimal IP that has no representations, only metadata.</description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/SIP/SIP33/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="SIP" version="2.2.0" requirementId="SIP33"/>
  <references>
    <reference requirementId="SIP33" URL="https://earksip.dilcis.eu/#SIP33"/>
  </references>
  <requirementText>
    <name>File format version</name>
    <location>mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION</location>
    <description>
      The version of the file format when the use of PREMIS has not been agreed upon in the submission agreement.
      Example: "1.0"
    </description>
    <cardinality>0..1</cardinality>
    <level>MAY</level>
  </requirementText>
  <description>
    mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION MAY exist.
    If mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION exists then it MUST have a value.
    The value MUST record the version of the file format.<!-- Untestable -->
    If mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION exists then the use of PREMIS
      MUST not have been agreed upon in the submission agreement.<!-- Untestable
      under the current wording as it would require parsing and interpreting the
      submission agreement, which is not a machine-readable document. If the
      requirement was about the presence of PREMIS metadata, some automated
      tests could be performed for the presence of PREMIS XML files or their
      references in amdSec/digiprovMD elements. However, such tests would likely
      remain inconclusive as "the presence of PREMIS" can be interpreted in
      multiple ways. -->
  </description>
  <dependencies>
    <dependency requirementId="Chapter_5.4" URL="https://earkcsip.dilcis.eu/#useofpremis">
      @sip:FILEFORMATVERSION should be used only if the use of PREMIS has not been agreed upon in the submission agreement.
    </dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION MAY exist.</description>
      <error level="INFO">
        <message>
          mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION does not exist. MAY be: the attribute exists and its value records the version of the file format.
        </message>
      </error>
      <corpusPackages>
        <package name="FILEFORMATVERSION_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/FILEFORMATVERSION_not_exist</path>
          <description>
            SIP where the METS.xml file has a mets/fileSec/fileGrp/file element with no @sip:FILEFORMATVERSION attribute.
          </description>
        </package>
        <package name="minimal_SIP_plus_mets_SHOULD_MAY_items" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_SIP_plus_mets_SHOULD_MAY_items</path>
          <description>
            Minimal SIP that matches all MUST requirements, plus all SHOULD and MAY requirements (both for elements and attributes).
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>If mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION exists then it MUST have a value.</description>
      <error level="WARNING"><!-- Empty values are not explicitly prohibited but go against the logic of the specification. -->
        <message>
          mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION value is empty. MUST be: if the attribute exists then it MUST have a value that records the version of the file format.
        </message>
      </error>
      <corpusPackages>
        <package name="FILEFORMATVERSION_value_empty" isValid="FALSE" isImplemented="TRUE" >
          <path>invalid/FILEFORMATVERSION_value_empty</path>
          <description>
            A SIP with METS.xml file that has a mets/fileSec/fileGrp/file/@sip:FILEFORMATVERSION = "".
          </description>
        </package>
        <package name="minimal_SIP_plus_mets_SHOULD_MAY_items" isValid="TRUE" isImplemented="TRUE">
          <path>valid/minimal_SIP_plus_mets_SHOULD_MAY_items</path>
          <description>
            Minimal SIP that matches all MUST requirements, plus all SHOULD and MAY requirements (both for elements and attributes).
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP65/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="CSIP" version="2.1.0" requirementId="CSIP65"/>
  <references>
    <reference requirementId="CSIP65" URL="https://earkcsip.dilcis.eu/#CSIP65"/>
    <reference requirementId="Sec521-the-use-of-identifiers" URL="https://earkcsip.dilcis.eu/#521-the-use-of-identifiers"/>
  </references>
  <requirementText>
    <name>File group identifier</name>
    <location>mets/fileSec/fileGrp/@ID</location>
    <description>
      An xml:id identifier for the file group used for internal package references. It must be unique within the package.
    </description>
    <cardinality>1..1</cardinality>
    <level>MUST</level>
  </requirementText>
  <description>The requirement links to 5.2.1. The use of identifiers and is mostly handled by XML schema validation. However, the ID attribute is optional according to METS.xsd, so this testcase has one rule to check if the ID attribute exists</description>
  <dependencies />
  <rules>
    <rule id="1">
      <description>There MUST be an ID attribute on every fileGrp</description>
      <error level="ERROR">
        <message>There MUST be an ID attribute on every fileGrp</message>
      </error>
      <corpusPackages>
        <package isValid="FALSE" isImplemented="FALSE" name="fileSec_missing_ID_attribute_at_fileGrp">
          <path>invalid/fileSec_missing_ID_attribute_at_fileGrp</path>
          <description>A package with a missing ID-attribute at one fileGrp</description>
        </package>
        <package isValid="FALSE" isImplemented="FALSE" name="fileSec_missing_ID_attribute_at_fileGrps">
          <path>invalid/fileSec_missing_ID_attribute_at_fileGrps</path>
          <description>A package with a missing ID attribute at two fileGrps</description>
        </package>
        <package isValid="TRUE" isImplemented="FALSE" name="minimal_IP_with_1_representation">
          <path>valid\minimal_IP_with_1_representation</path>
          <description>Minimal IP</description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>
